services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./api/db/data:/var/lib/postgresql/data
    shm_size: 128mb
    ports:
      - "5432:5432"
    restart: always
